CREATE DATABASE kino; 
USE kino;

CREATE TABLE users (
    Id int AUTO_INCREMENT, 
    Username VARCHAR(50) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Firstname VARCHAR(50) NOT NULL,
    Lastname VARCHAR(50) NOT NULL,
    Email VARCHAR(80) NOT NULL,
    PRIMARY KEY(Id)
);

CREATE TABLE film (
	Id int AUTO_INCREMENT, 
	UserID int NOT NULL,
	Titel VARCHAR(50) NOT NULL,
	Regisseur VARCHAR(50) NOT NULL,
	Genre VARCHAR(50) NOT NULL,
	Datum Date NOT NULL,
	Gedanke VARCHAR(500) NOT NULL,
	Dauern int NOT NULL,
	Poster VARCHAR(500) DEFAULT '0',
	PRIMARY KEY(Id)
);

CREATE TABLE topics (
	Id int AUTO_INCREMENT, 
	Topic VARCHAR(255) NOT NULL, 
	UserID int NOT NULL, 
	Datum TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	PRIMARY KEY(Id)
);

CREATE TABLE posts (Id int AUTO_INCREMENT, 
	Content VARCHAR(500) NOT NULL, 
	topicID int NOT NULL, 
	userID int NOT NULL, 
	Datum TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	PRIMARY KEY(Id)
);


